["pyproject.toml".tool.black]
line-length = 120

["pyproject.toml".tool.ruff]
select = ["E", "F"]

["setup.cfg".flake8]
select = "E265,F401,E266,E262"
exclude = ".git,venv,test"
max-line-length = 120
